### ISSUE TITLE
Get all projects using the api 

### ISSUE THREAD

**Issue by aliahmedmytoys** [DependencyTrack/dependency-track#2219] opened 2022-12-01 07:11 UTC
### Current Behavior

it only return 100 project and thats it not all projects and i need all projects to be returned

### Steps to Reproduce

dependency_track_url/v1/project using GET request
on my projects inside of it

### Expected Behavior

return all projects that exsist not only the first 100

### Dependency-Track Version

4.5.x

### Dependency-Track Distribution

Container Image

### Database Server

H2

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by stevespringett** [comment] 2022-12-01 19:45
Duplicate of #2193.  Questions should be asked in Slack.

**Closed by stevespringett** 2022-12-01 19:45 UTC
Labels: question
