### ISSUE TITLE
column ""PURL"" that has maximum length of 255. Please correct your data!

### ISSUE THREAD

**Issue by LIFEcmd** [DependencyTrack/dependency-track#2496] opened 2023-02-15 18:24 UTC
### Current Behavior

There is an exception after uploading the bom file. The maximum length of the purl column has been set to 1024, but the exception will still be thrown
![image](https://user-images.githubusercontent.com/66239815/219118289-a7633567-2fc7-488f-a18c-81dad9a76134.png)

The database structure has also been changed to 1024

### Steps to Reproduce

1.Upload the bom file and throw an exception when it is half processed

### Expected Behavior

This dependency should not be handled and no exception will be thrown

Lock in this position
src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
![image](https://user-images.githubusercontent.com/66239815/219118984-c4717c3e-216d-4a4f-a80a-607fdef43a56.png)

What should I do

### Dependency-Track Version

4.6.x

### Dependency-Track Distribution

Executable WAR

### Database Server

PostgreSQL

### Database Server Version

14

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by stevespringett** [comment] 2023-02-15 18:25
Duplicate of #2076

**Closed by stevespringett** 2023-02-15 18:25 UTC
Labels: defect, in triage
