### ISSUE TITLE
Add the possibility to automatically create projects

### ISSUE THREAD

**Issue by Mazorius** [DependencyTrack/dependency-track#189] opened 2018-08-14 08:11 UTC
### Issue Type:
  - [ ] defect report
  - [x] enhancement request
  
  
### Current Behavior:
Currently a project must be created in Dependency Track to add a Dependency Check Report.

### Steps to Reproduce (if defect):
-

### Expected Behavior:
If a project provides the Dependency Check Report for Dependency Track, Dependency Track should be able to automatically get the name of the project and its version.
If the project does not exist then it will be created or else the project will be updated.

### Environment:
  
  - Dependency-Track Version: 3.1.1
  - Distribution: Executable WAR
  - BoM Format & Version:
  - Database Server: PostgreSQL
  - Browser: Safari | Chrome

### Other Details:
-

**Comment by stevespringett** [comment] 2018-08-14 12:37
Duplicate of #168 . Project creation is performed over API when uploading a scan or bom, not by reading dependency check reports, which I have no plans to do.

**Closed** 2018-09-04 21:41 UTC
Labels: duplicate, pending release
