### ISSUE TITLE
Ability to organize several projects into one.

### ISSUE THREAD

**Issue by malchikserega** [DependencyTrack/dependency-track#857] opened 2020-11-30 10:57 UTC
### Current Behavior:
Currently we have following behaviour in DTrack UI.
For example we have **Project BIG** which contain multiple submodules/ subprojects like Project A and Project B. At this moment we can create (Project A,Version:1) and (Project B, Version:1), and in the web user interface we can see only list of this projects like:
**1. Project A, Version:1
2. Project B, Version: 1**
### Proposed Behavior:
My proposed behaviour and possible solution for issue which be described above:
In the web interface, the user should be able to organize any project into one. After this User can see all his projects like following list:
**1. Project BIG
   |_____Project A Version 1
   |_____Project B Version 1
2. Project C Version 1
3. Project BIG2
   |_____Project A Version 3
   |_____Project B Version 1**

**Comment by stevespringett** [comment] 2020-12-01 03:56
Duplicate of #84

**Closed** 2020-12-14 11:11 UTC
Labels: duplicate, enhancement
