### ISSUE TITLE
Parent shows not the sum of the childs

### ISSUE THREAD

**Issue by eL-Prova** [DependencyTrack/dependency-track#2410] opened 2023-01-26 13:06 UTC
### Current Behavior

Since last version it is possible to have an parent project with sub projects.
I should expect that the parent will sum the results of the childs.

It can also be possible that it was already know on the backlog but not yet finished,

### Steps to Reproduce

1. Have a parent project
2. Have 2 child projects
project_1 has 1 medium finding
project_2 has 1 low finding

### Expected Behavior

Parent shows everything empty and zero, but should expect parent project has 1 medium and 1 low.

### Dependency-Track Version

4.6.x

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by roadSurfer** [comment] 2023-01-26 19:33
Is this not a duplicate of #869?

**Comment by eL-Prova** [comment] 2023-01-29 11:12
Good point, I am not sure if I mean exactly the same, but I didnt found this issue in my search.

**Comment by rkg-mm** [comment] 2023-01-30 11:57
This is not a bug. It's simply a not yet implemented feature, see https://github.com/DependencyTrack/dependency-track/issues/2041

**Closed** 2024-12-10 18:20 UTC
Labels: duplicate
