### ISSUE TITLE
Licenses present in SBOM but not showing up in Dependency Track

### ISSUE THREAD

**Issue by mariuskimmina** [DependencyTrack/dependency-track#1494] opened 2022-03-24 09:58 UTC
### Current Behavior:

Uploading an SBOM (created with cyclonedx python tool) that contains license information leads to **no** license information in the dependency track ui.

<img width="1783" alt="image" src="https://user-images.githubusercontent.com/38843153/159890094-20d72b8a-3202-499f-a184-93a44968015d.png">

### Steps to Reproduce:

Create an SBOM with `cyclonedx-bom -e --format json` , Check that it contains license Information like this:

```
    {
      "type": "library",
      "bom-ref": "f07a70e9-e62d-4921-a472-e9d695525eec",
      "author": "Tarek Ziade",
      "name": "flake8",
      "version": "3.9.2",
      "licenses": [
        {
          "expression": "MIT"
        }
      ],
      "purl": "pkg:pypi/flake8@3.9.2"
    },
```

### Expected Behavior:

I would expect to see the MIT License to show up in the Dependency Track ui - but it doesn't.

### Environment:
  
  - Dependency-Track Version: v4.4.2
  - Distribution: Docker
  - BOM Format & Version: CycloneDX 
  - Database Server: Build in - I'm just using the docker-compose for testing purposes
  - Browser: Brave

**Comment by stevespringett** [comment] 2022-03-24 14:28
DT does not currently support SPDX expressions, only resolved SPDX license IDs and unresolved license names. 

Duplicate of #170

**Closed** 2022-03-25 08:28 UTC
Labels: duplicate
