### ISSUE TITLE
ERROR [TrivyAnalysisTask] An error occurred decrypting the Trivy API token

### ISSUE THREAD

**Issue by gadgesk** [DependencyTrack/dependency-track#4244] opened 2024-10-11 08:11 UTC
### Current Behavior

dependency-track-apiserver is not able to decrypt the api token from trivy. We set trivy in client server mode using docker-compose file.

### Steps to Reproduce

1. setp the trivy in analyzers in dependency track frontend URL.
2. pass the api token to the docker-compose file 
3. check the dependency-track-apiserver container
4. check for the logs of this container and grep for Trivy.
5. You will get this error

### Expected Behavior

dependency-track apiserver should be able to decrypt the api-token from trivy.

### Dependency-Track Version

4.7.x

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Browser

Google Chrome

### Checklist

- [x] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [x] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment] 2024-10-11 11:32
Duplicate of #2366. Please have a look at that issue and possibly share your logs. You should see any of these warnings in the log: https://github.com/DependencyTrack/dependency-track/pull/3651/files#diff-6b7af452fb5185907bc1b23443fef34d9f016c70248fecf72771c60cd0490d82R78-R93

**Closed by nscuro** 2024-10-11 11:32 UTC
Labels: duplicate

**Comment by gadgesk** [comment] 2024-10-14 05:26
Hi nscuro,

I have the below error logs in my dependency-track.log file. 

ERROR: Failed to decrypt value, possibly because it has been encrypted with a different key, or the encrypted value is corrupted. To verify the latter, please check the respective value in the database. For comparison, the base64-encoded value for which decryption was attempted has a length of 88, and a sha256 digest of %d. If this is different to what's stored in your database, please report this to https://github.com/DependencyTrack/dependency-track/issues/2366, so the root cause can be identified.

Could you please let me know which table and data do I need to check in database. I am using the volume mount in docker-compose file as ./volume/dependency-track:/data, but the dependency-track folder is empty. 

Could you please also let me know how we can encrypt and decrypt the data using new secret keys
