### ISSUE TITLE
Bom.xml showing zero components after upload (Version server V4.6.3)

### ISSUE THREAD

**Issue by ccfahe** [DependencyTrack/dependency-track#3732] opened 2024-05-19 06:23 UTC
### Current Behavior

I have my deptrack server running on open shift with API , Frontend and PostgreSql containers.
When I tried to upload bom.xml it showed zero components processed in spite of bom.xml having components.

Same bom.xml I tried with my local deptrack server and I can see all components.

The difference is in local I am using dep track container image to run server and in Openshift to run container along with potsgreSql

### Steps to Reproduce

1.I have my deptrack server running on open shift with API , Frontend and PostgreSql containers.
When I tried to upload bom.xml it showed zero components processed in spite of bom.xml having components.

Same bom.xml I tried with my local deptrack server and I can see all components.

The difference is in local I am using dep track container image to run server and in Openshift to run container along with potsgreSql

### Expected Behavior

It should show components 

### Dependency-Track Version

4.7.x

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment] 2024-05-19 10:18
Please consult the logs of your API server container running in OpenShift. If the BOM fails to be processed, you'll see error logs there. 

On a side note, 4.6.3 is now almost two years old. The current version is 4.11. If your issue is caused by a bug it is very likely that it is already fixed in a newer version. Please consider upgrading.

**Comment by nscuro** [comment] 2024-09-16 20:26
Newer versions of DT also include schema validation, which should make issues like this a lot more obvious to users and API clients. Closing this as no further details were provided and the solution is likely to just upgrade to a newer version.

**Closed by nscuro** 2024-09-16 20:26 UTC
Labels: rejected
