### ISSUE TITLE
Unable to start application with shipped `logback-json.xml` configuration

### ISSUE THREAD

**Issue by biehl1** [DependencyTrack/dependency-track#3127] opened 2023-10-23 18:47 UTC
### Current Behavior

Unable to start `dependencytrack/apiserver:4.9.0` with shipped `logback-json.xml` configuration. Apparently there are incompatibilities with library versions.

### Steps to Reproduce

```shell
$ docker run -e LOGGING_CONFIG_PATH=logback-json.xml --rm dependencytrack/apiserver:4.9.0
Exception in thread "main" java.lang.NoSuchMethodError: 'java.time.Instant ch.qos.logback.classic.spi.ILoggingEvent.getInstant()'
	at net.logstash.logback.composite.loggingevent.LoggingEventFormattedTimestampJsonProvider.getTimestampAsInstant(LoggingEventFormattedTimestampJsonProvider.java:29)
	at net.logstash.logback.composite.loggingevent.LoggingEventFormattedTimestampJsonProvider.getTimestampAsInstant(LoggingEventFormattedTimestampJsonProvider.java:25)
	at net.logstash.logback.composite.AbstractFormattedTimestampJsonProvider.writeTo(AbstractFormattedTimestampJsonProvider.java:164)
	at net.logstash.logback.composite.JsonProviders.writeTo(JsonProviders.java:78)
	at net.logstash.logback.composite.AbstractCompositeJsonFormatter.writeEventToGenerator(AbstractCompositeJsonFormatter.java:290)
	at net.logstash.logback.composite.AbstractCompositeJsonFormatter$JsonFormatter.writeEvent(AbstractCompositeJsonFormatter.java:190)
	at net.logstash.logback.composite.AbstractCompositeJsonFormatter.writeEvent(AbstractCompositeJsonFormatter.java:156)
	at net.logstash.logback.encoder.CompositeJsonEncoder.encode(CompositeJsonEncoder.java:106)
	at net.logstash.logback.encoder.CompositeJsonEncoder.encode(CompositeJsonEncoder.java:92)
	at net.logstash.logback.encoder.CompositeJsonEncoder.encode(CompositeJsonEncoder.java:36)
	at ch.qos.logback.core.OutputStreamAppender.subAppend(OutputStreamAppender.java:230)
	at ch.qos.logback.core.OutputStreamAppender.append(OutputStreamAppender.java:102)
	at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
	at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
	at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)
	at ch.qos.logback.classic.Logger.info(Logger.java:579)
	at alpine.embedded.EmbeddedJettyServer.main(EmbeddedJettyServer.java:59)
``` 

### Expected Behavior

Application starts ok, logs are output in json format.

### Dependency-Track Version

4.9.0

### Dependency-Track Distribution

Container Image

### Database Server

N/A

### Browser

N/A

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment] 2023-10-23 19:09
Thanks for reporting. The cause is an erroneous update of the JSON encoder library in Alpine, the framework DT is based on. I raised https://github.com/DependencyTrack/dependency-track/pull/3128 and verified that it fixes the issue. This will be shipped with 4.9.1, which will be released shortly.

**Closed** 2023-10-23 20:19 UTC
Labels: defect
