### ISSUE TITLE
Snyk analyzer configuration

### ISSUE THREAD

**Issue by rysearle** [DependencyTrack/dependency-track#4290] opened 2024-10-22 12:10 UTC
### Current Behavior

Today, the [Snyk analyzer configuration](https://docs.dependencytrack.org/datasources/snyk/) does not validate the API token has the relevant permissions to perform the analysis. This means that users do not realize that Snyk is unable to analyze their SBOMs until after an analysis is triggered — and they are left trying to debug.

One example of this is that the API that powers the Snyk analyzer is only available to Enterprise accounts, meaning only API tokens from entitled orgs will be able to make successful requests. Team, trial, and free users who attempt to use their personal access token receive no error information during configuration. 

### Proposed Behavior

While configuring the Snyk analyzer, when entering a token there should be validation. Dependency-Track should make a sample request to Snyk's API using the configured token, and if the request fails due to lack of permissions (e.g. 401, 403) the field should not display a ✅ and instead display an error message, and the user should not be able to "update" their configuration. 

![Image](https://github.com/user-attachments/assets/810b72e2-25f4-413b-9168-8f618e752ff9)

### Checklist

- [x] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [x] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this enhancement was already requested

**Comment by msymons** [comment] 2024-10-23 08:32
This is duplicate of #2395, which requests a "Test Connection" button for the Snyk configuration screen.

**Closed by msymons** 2024-10-23 08:32 UTC
Labels: enhancement
