### ISSUE TITLE
Portfolio Access Control rules do not apply to child projects

### ISSUE THREAD

**Issue by andreyeto** [DependencyTrack/dependency-track#2332] opened 2022-12-28 14:37 UTC
### Current Behavior

When you add a project with a childs to some team in Portfolio Access Control, members of this team have access **only** to the parent project.

### Steps to Reproduce

1. Enable Portfolio Access Control
2. Create a project hierarchy (parent with some childs)
3. Grant access to the parent project for some team in Portfolio Access Control
4. Login with the team's member account

### Expected Behavior

Parent and child projects should be accessible.

### Dependency-Track Version

4.7.0

### Dependency-Track Distribution

Container Image

### Database Server

N/A

### Browser

N/A

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by rkg-mm** [comment] 2023-01-09 11:43
duplicate of https://github.com/DependencyTrack/dependency-track/issues/2042

**Comment by msymons** [comment] 2023-01-09 11:50
As stated, duplicate of #2042

**Closed by msymons** 2023-01-09 11:50 UTC
Labels: defect, duplicate, access control
