### ISSUE TITLE
StackOverflowError when processing sbom for the second time

### ISSUE THREAD

**Issue by antrix** [DependencyTrack/dependency-track#4086] opened 2024-08-22 02:58 UTC
### Current Behavior

When processing the offending SBOM for the second time, the `BomUploadProcessingTask` fails with a `StackOverflowError`. 

This is on `v4.11.6`

> 2024-08-22 02:50:07,082 ERROR [LoggableUncaughtExceptionHandler] An unknown error occurred in an asynchronous event or notification thread
java.lang.StackOverflowError: null
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.readUTFBody(Unknown Source)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.readUTF(Unknown Source)
	at java.base/java.io.ObjectInputStream.readUTF(Unknown Source)
	at java.base/java.io.ObjectStreamClass.readNonProxy(Unknown Source)
	at java.base/java.io.ObjectInputStream.readClassDescriptor(Unknown Source)
	at java.base/java.io.ObjectInputStream.readNonProxyDesc(Unknown Source)
	at java.base/java.io.ObjectInputStream.readClassDesc(Unknown Source)
	at java.base/java.io.ObjectInputStream.readEnum(Unknown Source)
	at java.base/java.io.ObjectInputStream.readObject0(Unknown Source)
	at java.base/java.io.ObjectInputStream$FieldValues.<init>(Unknown Source)
	at java.base/java.io.ObjectInputStream.readSerialData(Unknown Source)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
	at java.base/java.io.ObjectInputStream.readObject0(Unknown Source)
	at java.base/java.io.ObjectInputStream.readObject(Unknown Source)
	at java.base/java.io.ObjectInputStream.readObject(Unknown Source)
	at java.base/java.util.ArrayList.readObject(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at java.base/java.io.ObjectStreamClass.invokeReadObject(Unknown Source)
	at java.base/java.io.ObjectInputStream.readSerialData(Unknown Source)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
	at java.base/java.io.ObjectInputStream.readObject0(Unknown Source)
	at java.base/java.io.ObjectInputStream.readObject(Unknown Source)
	at java.base/java.io.ObjectInputStream.readObject(Unknown Source)
	at org.datanucleus.store.rdbms.mapping.column.BlobImpl.getObject(BlobImpl.java:120)
	at org.datanucleus.store.rdbms.mapping.column.AbstractLargeBinaryColumnMapping.getObjectForBytes(AbstractLargeBinaryColumnMapping.java:255)
	at org.datanucleus.store.rdbms.mapping.column.AbstractLargeBinaryColumnMapping.getObject(AbstractLargeBinaryColumnMapping.java:389)
	at org.datanucleus.store.rdbms.mapping.java.AbstractContainerMapping.getObject(AbstractContainerMapping.java:281)
	at org.datanucleus.store.rdbms.fieldmanager.ResultSetGetter.fetchObjectField(ResultSetGetter.java:181)
	at org.datanucleus.state.StateManagerImpl.replacingObjectField(StateManagerImpl.java:2069)
	at org.dependencytrack.model.Component.dnReplaceField(Component.java)
	at org.dependencytrack.model.Component.dnReplaceFields(Component.java)
	at org.datanucleus.state.StateManagerImpl.replaceFields(StateManagerImpl.java:4369)
	at org.datanucleus.state.StateManagerImpl.replaceFields(StateManagerImpl.java:4393)
	at org.datanucleus.store.rdbms.request.FetchRequest.execute(FetchRequest.java:521)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.fetchObject(RDBMSPersistenceHandler.java:427)
	at org.datanucleus.state.StateManagerImpl.loadFieldsFromDatastore(StateManagerImpl.java:1632)
	at org.datanucleus.state.StateManagerImpl.refreshFieldsInFetchPlan(StateManagerImpl.java:4034)
	at org.datanucleus.api.jdo.state.PersistentNontransactional.transitionRefresh(PersistentNontransactional.java:93)
	at org.datanucleus.state.StateManagerImpl.refresh(StateManagerImpl.java:1031)
	at org.datanucleus.ExecutionContextImpl.refreshObject(ExecutionContextImpl.java:1664)
	at org.datanucleus.api.jdo.JDOPersistenceManager.jdoRefresh(JDOPersistenceManager.java:490)
	at org.datanucleus.api.jdo.JDOPersistenceManager.refresh(JDOPersistenceManager.java:507)
	at alpine.persistence.AbstractAlpineQueryManager.persist(AbstractAlpineQueryManager.java:430)
	at org.dependencytrack.persistence.ComponentQueryManager.createComponent(ComponentQueryManager.java:348)
	at org.dependencytrack.persistence.QueryManager.createComponent(QueryManager.java:565)
	at org.dependencytrack.tasks.BomUploadProcessingTask.processComponent(BomUploadProcessingTask.java:252)
	at org.dependencytrack.tasks.BomUploadProcessingTask.processComponent(BomUploadProcessingTask.java:262)
	at org.dependencytrack.tasks.BomUploadProcessingTask.processComponent(BomUploadProcessingTask.java:262)
	at org.dependencytrack.tasks.BomUploadProcessingTask.processComponent(BomUploadProcessingTask.java:262)
	at org.dependencytrack.tasks.BomUploadProcessingTask.processComponent(BomUploadProcessingTask.java:262)
	at org.dependencytrack.tasks.BomUploadProcessingTask.processComponent(BomUploadProcessingTask.java:262)
	at org.dependencytrack.tasks.BomUploadProcessingTask.processComponent(BomUploadProcessingTask.java:262)

### Steps to Reproduce

1. Create a new project
2. Upload offending SBOM and let it complete processing
3. Upload the SBOM again
4. Stackoverflow error

The sbom & the full stack trace are in this gist: https://gist.github.com/antrix/6308d85aa9f7c6918073fd7505a79f1a

### Expected Behavior

Bom processing should not fail

### Dependency-Track Version

4.11.6

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by antrix** [comment] 2024-10-01 14:28
Checking if I can provide any other data for this?

**Comment by nscuro** [comment] 2024-10-01 14:31
Duplicate of #3715. Please check that issue for [guidance](https://github.com/DependencyTrack/dependency-track/issues/3715#issuecomment-2114296134).

**Closed by nscuro** 2024-10-01 14:31 UTC
Labels: duplicate
