### ISSUE TITLE
Unable to upload sbom file 

### ISSUE THREAD

**Issue by visagansanthanam-unisys** [DependencyTrack/dependency-track#3031] opened 2023-09-14 07:17 UTC
### Current Behavior

When I try to upload the SBOM file via UI (Upload BOM), i get a successfully updated message. However i don't see any component on the project. While analysing the API log i found following error message.

`2023-09-14 07:07:52,138 ERROR [BomUploadProcessingTask] Error while processing bom
org.cyclonedx.exception.ParseException: Unable to parse BOM from byte array
	at org.cyclonedx.parsers.JsonParser.parse(JsonParser.java:70)
	at org.dependencytrack.tasks.BomUploadProcessingTask.inform(BomUploadProcessingTask.java:105)
	at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:101)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.util.ArrayList<org.cyclonedx.model.Tool>` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: (byte[])"{
  "bomFormat": "CycloneDX",
  "specVersion": "1.5",
  "serialNumber": "urn:uuid:a4da8087-25bb-4b89-98b9-f2b6c368d6a1",
  "version": 1,
  "metadata": {
    "timestamp": "2023-09-14T05:24:09.218Z",
    "tools": {
      "components": [
        {
          "group": "@cyclonedx",
          "name": "cdxgen",
          "version": "9.3.1",
          "purl": "pkg:npm/%40cyclonedx/cdxgen@9.3.1",
          "type": "application",
          "bom-ref": "pkg:npm/@cyclonedx/cdxgen@9.3.1"
        }
      ]
   "[truncated 46201 bytes]; line: 8, column: 14] (through reference chain: org.cyclonedx.model.Bom["metadata"]->org.cyclonedx.model.Metadata["tools"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1746)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1520)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1467)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.handleNonArray(CollectionDeserializer.java:396)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:252)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4730)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3738)
	at org.cyclonedx.parsers.JsonParser.parse(JsonParser.java:68)
	... 5 common frames omitted
2023-09-14 07:07:52,175 DEBUG [NotificationService] Dispatching notification: class alpine.notification.Notification
2023-09-14 07:07:52,175 DEBUG [NotificationService] Alerting subscriber org.dependencytrack.notification.NotificationRouter
2023-09-14 07:07:52,175 DEBUG [EventService] Dispatching event: class org.dependencytrack.event.IndexEvent
2023-09-14 07:07:52,175 DEBUG [EventService] Alerting subscriber org.dependencytrack.tasks.IndexTask
2023-09-14 07:07:52,179 DEBUG [EventService] Dispatching event: class org.dependencytrack.event.IndexEvent
2023-09-14 07:07:52,179 DEBUG [EventService] Alerting subscriber org.dependencytrack.tasks.IndexTask
2023-09-14 07:07:52,179 DEBUG [EventService] Calling onSuccess
2023-09-14 07:07:52,179 DEBUG [EventService] Calling onSuccess
2023-09-14 07:07:52,185 DEBUG [EventService] Calling onSuccess`

### Steps to Reproduce

1. Login into DependencyTrack UI
2. Navigate to the Project > Components
3. Click on Upload BOM
4. Select the BOM file (file [attached)](url)
[bom.zip](https://github.com/DependencyTrack/dependency-track/files/12605879/bom.zip)
5. Click Upload, a success message will appear on the UI but the upload will fail at the api level

### Expected Behavior

BOM file need to uploaded and processed successfully

### Dependency-Track Version

4.8.2

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment] 2023-09-14 08:34
Duplicate of #2850. Import of CycloneDX v1.5 BOMs will be supported in DT v4.9.

In the meantime, consider using the `--spec-version 1.4` for cdxgen.

**Closed by nscuro** 2023-09-14 08:34 UTC
Labels: duplicate
