### ISSUE TITLE
A field with a length greater than 255 is causing an error during BOM processing.

### ISSUE THREAD

**Issue by khaledgithubwl** [DependencyTrack/dependency-track#3613] opened 2024-04-11 09:54 UTC
### Current Behavior

uploading a bom that has a field with a length greater than 255 is causing an error during BOM processing.
getting this error : ERROR [org.dependencytrack.tasks.BomUploadProcessingTask] Error while processing bom
org.datanucleus.exceptions.NucleusUserException: Attempt to store value  ... PURL"" that has maximum length of 255. Please correct your data! 

### Steps to Reproduce

1.uploading a bom that  has a field with a length greater than 255 

### Expected Behavior

it should not stop the bom processing task.

### Dependency-Track Version

4.10.1

### Dependency-Track Distribution

Executable WAR

### Database Server

PostgreSQL

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment] 2024-04-11 10:01
Duplicate of https://github.com/DependencyTrack/dependency-track/issues/2076, fixed with https://github.com/DependencyTrack/dependency-track/pull/3560, will ship with the upcoming v4.11 release.

**Closed by nscuro** 2024-04-11 10:01 UTC
Labels: defect, in triage
