### ISSUE TITLE
Dependency Track shows Release Candidates and preversions as update for "deprecated" components

### ISSUE THREAD

**Issue by phoenixadb** [DependencyTrack/dependency-track#2664] opened 2023-04-11 12:59 UTC
### Current Behavior

Dependency Track shows deprecated components and proposes RC versions instead.

![dependency_track](https://user-images.githubusercontent.com/2065650/231168033-2bc5073e-780d-4633-8ea1-b869d4cb5a57.png)

### Steps to Reproduce

1. Upload a **SBOM** file containing **com.fasterxml.jackson.core:jackson-databind** in **2.13.2.1** version
2. Check the list of the components

### Expected Behavior

RC, Alpha and Beta versions should not be proposed as versions to replace deprecated components.
They are considered either unapproved or unstable. This will lead to possible malfunctions if replaced and could impact production platforms or solutions. 

### Dependency-Track Version

4.7.1

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Browser

Mozilla Firefox

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by msymons** [comment] 2023-04-12 12:21
This is a duplicate of #513.

There is a proposed solution (#2501) that is scheduled for milestone 4.9.

**Closed by msymons** 2023-04-12 12:21 UTC
Labels: duplicate
