### ISSUE TITLE
Description for PUT and POST requests

### ISSUE THREAD

**Issue by tapmch** [DependencyTrack/dependency-track#3765] opened 2024-05-28 13:21 UTC
### Current Behavior

![dtrack](https://github.com/DependencyTrack/dependency-track/assets/132920574/19bef7ae-0ffb-4c64-8534-befc4a8ee883)

### Steps to Reproduce

1. In the swagger json the description for post requests relates to updates whereas put requests relate to creation. Shouldn't it be the opposite?

### Expected Behavior

POST -> create
PUT -> update

### Dependency-Track Version

4.7.x

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Database Server Version

13.5

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by aravindparappil46** [comment] 2024-05-28 15:12
I agree with @nscuro.

According to[ IETF RFC 9110](https://datatracker.ietf.org/doc/html/rfc9110#name-put), PUT can also be for creates:
> The PUT method requests that the state of the [target resource](https://datatracker.ietf.org/doc/html/rfc9110#target.resource) be **created** **or** **replaced** with the state defined by the representation enclosed in the request message content

Best not to spend too much time on semantics here.

**Comment by tapmch** [comment] 2024-05-28 16:50
PUT is idempotent (where POST is not) which in my opinion makes PUT more suitable for updates. But I agree, I didn't want to start a long discussion here. Feel free to close the issue.

**Comment by markusmuellerusi** [comment] 2024-05-29 06:37
https://restfulapi.net/http-methods/
It is a common practice to use put for updates, patch for partial updates and post for creating resources. The response for creating with post is 201 (created), for updating 200 (ok). All rest APIs I know, use this pattern except alpine. The issue is not a swagger, it's the implementation in dtrack and alpine in using http verbs. But I think, it will be a big and incompatible change with an impact on frontend and all public APIs. So dtrack should keep its implementation.

**Comment by nscuro** [comment] 2024-05-29 09:13
Closing for now, but still appreciate everyone's input. I think we can / should re-evaluate this when we start adding `/v2` endpoints, where we don't have to worry about breaking changes.

**Closed by nscuro** 2024-05-29 09:13 UTC
Labels: wontfix
