### ISSUE TITLE
Project Details view cannot be opened (missing UUID in URL -> Error 500)

### ISSUE THREAD

**Issue by rkg-mm** [DependencyTrack/dependency-track#4048] opened 2024-01-27 15:54 UTC
### Current Behavior

I am unable to open the "View Details" window of some of our projects. Others work fine. The problematic projects try to request 
/api/v1/project/undefined

Somehow the projects UUID is not available when creating the URL, resulting in an "undefined" instead of the UUID. This causes a ERROR 500 on the server due to the missing ID. (Shouldn't this be a 400?)

### Steps to Reproduce

1. Open a project (it only happens on some projects, no idea why on these and not on others)
2. Click "View Details"
3. See the error

### Expected Behavior

No error

### Dependency-Track Frontend Version

4.10.0

### Browser

Mozilla Firefox

### Operating System

Windows

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/frontend/issues) for whether this defect was already reported

**Comment by nscuro** [comment] 2024-08-08 12:36
Think I found the cause, although I don't 100% understand it since I'm not well versed in the ORM internals.

In DT v4.11.x and earlier (based on Alpine v2.2.5 or earlier), the `QueryManager#getObjectByUuid` method did not close the `Query` object after the result is obtained: https://github.com/stevespringett/Alpine/blob/fb371ee69c937e7f1bc6cdf022010d7a705a4f00/alpine-infra/src/main/java/alpine/persistence/AbstractAlpineQueryManager.java#L546-L551

As of DT v4.12 (based on Alpine v3), `Query` objects are now properly closed: https://github.com/stevespringett/Alpine/blob/59996ba6d05d4d146802ab981628deccd9e0c6cd/alpine-infra/src/main/java/alpine/persistence/AbstractAlpineQueryManager.java#L479-L484

Changing the `#getObjectByUuid` method used here: https://github.com/DependencyTrack/dependency-track/blob/9dca633c0ce4daa759c0f7542b60d4fa7183e2ca/src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java#L218-L220

To an implementation that closes the query, like this one: https://github.com/DependencyTrack/dependency-track/blob/9dca633c0ce4daa759c0f7542b60d4fa7183e2ca/src/main/java/org/dependencytrack/persistence/QueryManager.java#L1359-L1366

Fixes the issue. So it seems there is some form of lazy-loading at play here, that is never forced to complete because the backing `Query` was never getting closed.

So two good news:

* This particular issue can be fixed in v4.11.6 without additional overhead
* This entire class of bugs will be resolved in v4.12.0

**Closed** 2024-08-08 13:14 UTC
Labels: defect, p2, size/S

**Comment by rkg-mm** [comment] 2024-08-08 15:20
Great, thank you for the analysis!
