### ISSUE TITLE
javax.jdo.JDOUserException when making HTTP GET to /api/v1/project/ with name parameter

### ISSUE THREAD

**Issue by csansone-handy** [DependencyTrack/dependency-track#543] opened 2019-12-10 14:50 UTC
### Current Behavior:
When making an HTTP GET to the `/api/v1/project` endpoint an HTTP 500 error is thrown if the `name` parameter is specified. However, if the `name` parameter is omitted and instead the `searchText` or `filter` parameter is used then the HTTP GET returns appropriately.

### Steps to Reproduce:
Run the following command: `curl -X GET --header 'Accept: application/json' --header 'X-Api-Key: <api_key>' 'https://my-dtrack-instance.com/api/v1/project?name=my-proj-name'`

### Expected Behavior:
We should be able to filter on name directly instead of using a wildcard match with `searchText` or `filter`

### Environment:
  
  - Dependency-Track Version: 3.6.1
  - Distribution: Docker image running on Kubernetes
  - BOM Format & Version: N/A
  - Database Server: PostgreSQL
  - Browser: curl

#### Stack Trace:
```
2019-12-04 16:23:41,652 [] WARN [org.eclipse.jetty.server.HttpChannel] /api/v1/project/
javax.servlet.ServletException: javax.jdo.JDOUserException: Portion of expression could not be parsed: )
NestedThrowables:
org.datanucleus.store.query.QueryCompilerSyntaxException: Portion of expression could not be parsed: )
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:408)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:365)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:318)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:852)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
        at alpine.filters.ContentSecurityPolicyFilter.doFilter(ContentSecurityPolicyFilter.java:224)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
        at alpine.filters.ClickjackingFilter.doFilter(ClickjackingFilter.java:92)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
        at alpine.filters.WhitelistUrlFilter.doFilter(WhitelistUrlFilter.java:115)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1583)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:536)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1581)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1307)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:482)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1549)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1204)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:494)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:374)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:367)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918)
        at java.lang.Thread.run(Thread.java:748)
Caused by: javax.jdo.JDOUserException: Portion of expression could not be parsed: )
at org.datanucleus.api.jdo.NucleusJDOHelper.getJDOExceptionForNucleusException(NucleusJDOHelper.java:635)
        at org.datanucleus.api.jdo.JDOQuery.executeInternal(JDOQuery.java:456)
        at org.datanucleus.api.jdo.JDOQuery.execute(JDOQuery.java:276)
        at alpine.persistence.AbstractAlpineQueryManager.getCount(AbstractAlpineQueryManager.java:293)
        at alpine.persistence.AbstractAlpineQueryManager.execute(AbstractAlpineQueryManager.java:142)
        at org.dependencytrack.persistence.QueryManager.getProjects(QueryManager.java:203)
        at org.dependencytrack.resources.v1.ProjectResource.getProjects(ProjectResource.java:79)
        at sun.reflect.GeneratedMethodAccessor267.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:392)
        ... 41 common frames omitted
Caused by: org.datanucleus.store.query.QueryCompilerSyntaxException: Portion of expression could not be parsed: )
        at org.datanucleus.query.compiler.JDOQLParser.parse(JDOQLParser.java:96)
        at org.datanucleus.query.compiler.JavaQueryCompiler.compileFilter(JavaQueryCompiler.java:600)
        at org.datanucleus.query.compiler.JDOQLCompiler.compile(JDOQLCompiler.java:104)
        at org.datanucleus.store.query.AbstractJDOQLQuery.compileGeneric(AbstractJDOQLQuery.java:373)
        at org.datanucleus.store.query.AbstractJDOQLQuery.compileInternal(AbstractJDOQLQuery.java:431)
        at org.datanucleus.store.rdbms.query.JDOQLQuery.compileInternal(JDOQLQuery.java:263)
        at org.datanucleus.store.query.Query.executeQuery(Query.java:1928)
        at org.datanucleus.store.query.Query.executeWithArray(Query.java:1856)
        at org.datanucleus.api.jdo.JDOQuery.executeInternal(JDOQuery.java:433)
        ... 67 common frames omitted
```

**Comment by csansone-handy** [comment] 2019-12-10 14:50
Reference Slack chat: https://owasp.slack.com/archives/C6R3R32H4/p1575477414312200

**Comment by stevespringett** [comment] 2019-12-10 15:08
Note to self: I as not able to reproduce locally or with the unit tests which test the name parameter in question. I was however able to reproduce on a local DT instance which had been running for months. In my case, the stack trace ended up being in the server.log, not the dependency-track.log

**Comment by stevespringett** [comment] 2019-12-12 19:34
After a bit of investigation, this appears to be a duplicate of #462.

**Closed** 2019-12-16 16:30 UTC
Labels: defect, duplicate, p2, pending release
