### ISSUE TITLE
Exported SBOMs contain circular references

### ISSUE THREAD

**Issue by flemminglau** [DependencyTrack/dependency-track#3025] opened 2023-09-11 10:30 UTC
### Current Behavior

Looking in the dependency graph I have the following dependencies:

![image](https://github.com/DependencyTrack/dependency-track/assets/25148089/106821b9-5e7b-4c7e-893e-7a3fef5ece8b)

When exporting that inventory to an SBOM I get:

![image](https://github.com/DependencyTrack/dependency-track/assets/25148089/5f9a8909-588d-40b5-b510-891a34a60c42)

You will have to trust me when I say that the first reference of the 3 (`...16a83`) is pointing back to the parent and the other 2 are the actual children.

As a result downstream systems complain that the dependency tree contains circular references.

I have a number of these in the files I am looking at but have no idea how widespread this issue is or what triggers it.

### Steps to Reproduce

Export inventory having dependency information to an SBOM json file.

It is not clear if the data must somehow be special.

### Expected Behavior

The SBOM file ref.dependsOn information should list child items only.
Not include parent items.

### Dependency-Track Version

4.8.2

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment] 2023-09-11 10:36
Does the original BOM that was uploaded to DT also have circular dependencies? Specifically, how does this particular dependency relationship look in the original BOM?

**Comment by flemminglau** [comment] 2023-09-11 10:57
Ouch.

It turns out that this same relationship is defined in the originally uploaded SBOM:

![image](https://github.com/DependencyTrack/dependency-track/assets/25148089/8ba44bf4-4f5e-4af3-b981-7c0ccdcc9c60)

So it seems this wrong data survives being stored in DT, exported to an SBOM, merged with other SBOMs and loaded back into DT.

I guess the only thing I could complain about would be that DT does not flag it as an issue when uploading the original SBOM.
(Have not checked the logs)

**Comment by nscuro** [comment] 2023-09-11 11:05
What tool was the SBOM generated with?

@jkowalleck Are circular dependencies common / to be expected in the NPM ecosystem?

**Comment by nscuro** [comment] 2023-09-11 11:08
> @flemminglau I guess the only thing I could complain about would be that DT does not flag it as an issue when uploading the original SBOM.

It may be counter-intuitive, but circular dependencies in general are a thing (I know of multiple occurrences in the Go ecosystem), so it's sadly nothing DT can prevent on its own. Either the ecosystem / package managers themselves need to prevent it, or the BOM generators should do it. But even then, the fact that a dependency is circular is *probably* something you want to know, when it happens.

**Comment by jkowalleck** [comment] 2023-09-11 13:17
> @jkowalleck Are circular dependencies common / to be expected in the NPM ecosystem?

Yes. Indeed, circular dependencies are a thing in NPM. NPM/Yarn/PNPM resolve them internally.
These dependencies might not be declared explicitly by package-authors, but they might be caused by so called "peerDependencies".
read <https://docs.npmjs.com/cli/v6/configuring-npm/package-json#peerdependencies>
read <https://docs.npmjs.com/cli/v7/using-npm/config#strict-peer-deps>

----

lets fabricate an example, that leans to real-world usage:
* there is a tool/framework "Framework".
* there is a library "F-Plugin", which is also a plugin for "Framework".
* "Framework" defines "F-Plugin" as a core-plugin and declares it as a direct dependency.
* "F-Plugin" may exist alone, but only works with a certain version `^1.33.7` of "Framework"

Then the relationship might be as follows:
* "Framework" depends on "F-Plugin@^1.0.1"
* "F-Plugin" depends on nothing in particular
* "F-Plugin" declares the peerDependencies as "Framework@1.33.7"

This results in a node-module-tree where
(heavily depends on <https://docs.npmjs.com/cli/v7/using-npm/config#strict-peer-deps> and other settings and flags)
* "Framework" MUST NOT be nested in "F-Plugin"
* "Framework" must be installed in a certain version, in order to allow "F-Plugin" to being installed

**Comment by flemminglau** [comment] 2023-09-11 13:22
So is the conclusion that circular references are not an error? They can be true?

E.g. SBOM management systems should not consider them as being "invalid data"?

**Comment by nscuro** [comment] 2023-09-14 08:37
> So is the conclusion that circular references are not an error? They can be true?

Correct.

With this in mind, I don't see a defect in DT and will close this issue.

@flemminglau, in case you want DT to handle circular references differently, or make them more obvious to users, please raise an enhancement request for that.

**Closed by nscuro** 2023-09-14 08:37 UTC
Labels: not an issue
