### ISSUE TITLE
Add titles to API keys

### ISSUE THREAD

**Issue by T0hha** [DependencyTrack/dependency-track#250] opened 2018-12-04 13:51 UTC
It would be nice to have a possibility to add titles to the API keys or to link projects with API keys so specific API key could access only to a specific project.

### Issue Type:
  - enhancement request

**Comment by stevespringett** [comment] 2018-12-04 15:58
Duplicate of #140 

This feature will be coming in a future release. Likely, sometime in 2019.

**Closed by stevespringett** 2018-12-04 15:58 UTC
Labels: duplicate
