### ISSUE TITLE
alpine-parent is not available

### ISSUE THREAD

**Issue by markusmuellerusi** [DependencyTrack/dependency-track#3766] opened 2024-05-28 15:58 UTC
### Current Behavior

apline projects are required to be published on maven repo. 2.2.6 is missing.
(no snapshots, real versions)

### Steps to Reproduce

1. https://oss.sonatype.org/ has no official version -> https://oss.sonatype.org/#nexus-search;gav~us.springett~alpine-parent~~~~kw,versionexpand
2. https://mvnrepository.com/artifact/us.springett/alpine-executable-war

### Expected Behavior

Provide used artefacts in official repos.

### Dependency-Track Version

4.11.1

### Dependency-Track Distribution

Executable WAR

### Database Server

Microsoft SQL Server

### Browser

Microsoft Edge

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment] 2024-05-28 16:07
Alpine snapshots are published to the OSSRH snapshot repository, e.g. https://oss.sonatype.org/content/repositories/snapshots/us/springett/alpine-common/

This repository is configured in Dependency-Track's POM: https://github.com/DependencyTrack/dependency-track/blob/1f2cc281a14de473485f35846e96f89a738bf321/pom.xml#L142-L151

Releasing new versions of Alpine for every single change is currently not practical for us. A new version of Alpine will be released and published to Maven Central when we are certain that it's fully operational and doesn't cause any regressions in DT.

**Comment by markusmuellerusi** [comment] 2024-05-29 06:10
![Repositories](https://github.com/DependencyTrack/dependency-track/assets/11981532/cb96ea74-667e-40e3-9900-7f6197066daa)
Then please publish Alpine 2.2.6. It's missing. I do not really want to use a snapshot. But 2.2.6 has the run-in-transaction, which in used in Dependency-Track 4.11. Thanks in advance and best wishes.

**Comment by nscuro** [comment] 2024-05-29 09:12
I get the frustration, in particular when your organization does not allow consumption from external snapshot repositories.

> Then please publish Alpine 2.2.6. It's missing. I do not really want to use a snapshot. But 2.2.6 has the run-in-transaction, which in used in Dependency-Track 4.11.

Version 4.11.x of Dependency-Track is using Alpine 2.2.5: https://github.com/DependencyTrack/dependency-track/blob/a0c5045bb700aa1e03bbc33db286717f367c7727/pom.xml#L24-L28

Note that the `master` branch is used for the next minor version (hence being `4.12.0-SNAPSHOT`). We create separate release branches (i.e. `4.11.x` as linked above) for backporting any critical bugfixes.

Version 2.2.6 of Alpine will never be released. Due to various larger changes, among them:

* https://github.com/stevespringett/Alpine/pull/567
* https://github.com/stevespringett/Alpine/pull/570

`2.2.6-SNAPSHOT` has been changed to `3.0.0-SNAPSHOT`. Dependency-Track `4.12.0-SNAPSHOT` has migrated to Alpine `3.0.0-SNAPSHOT` via https://github.com/DependencyTrack/dependency-track/pull/3730, which was merged yesterday.

**Comment by nscuro** [comment] 2024-05-29 09:19
If you want to contribute a bugfix (not a feature), you could base your work on the `4.11.x` branch and raise a PR into that. We can then take care of porting the fix to `master`.

Usually we do it the other way around (backporting from `master` to `4.11.x`), but in the end it doesn't really matter.

**Comment by markusmuellerusi** [comment] 2024-06-03 07:01
Thanks a lot for the clarification!

**Closed** 2024-06-03 17:34 UTC
Labels: wontfix
