### ISSUE TITLE
Permissions do not follow the evolution of the project versions

### ISSUE THREAD

**Issue by step50** [DependencyTrack/dependency-track#1632] opened 2022-05-17 10:09 UTC
### Current Behavior:
The permissions do not follow the evolution of the project versions

### Steps to Reproduce:
- Create a project with N teams in version 1.0.0
- menu "Portfolio Access Control", the N teams are affected to the project (section 'Project access')
- menu "Project", we have one line for this project
- menu "Project Detail", select 'Add version' and create a new version for this project 1.0.1  with the all include parameters (tags, properties, components, services, audit history)
- menu "Project", we have now 2 lines for this project. The first line with the version 1.0.0 and a second with 1.0.1
- menu "Portfolio Access Control", the N teams are affected only to the project with the version 1.0.0 (section 'Project access') , not the project with the version 1.0.1

### Expected Behavior:
- Create a project with N teams in version 1.0.0
- menu "Portfolio Access Control", the N teams are affected to the project (section 'Project access')
- menu "Project", we have one line for this project
- menu "Project Detail", select 'Add version' and create a new version for this project 1.0.1  with the all include parameters (tags, properties, components, services, audit history). Need to add a parameter for permissions ?
- menu "Project", we have now 2 lines for this project. The first line with the version 1.0.0 and a second with 1.0.1
- menu "Portfolio Access Control", the N teams are affected to the project with the version 1.0.0 (section 'Project access') AND the the version 1.0.1

OR

- Create a project with N teams in version 1.0.0
- menu "Portfolio Access Control", the N teams are affected to the project (section 'Project access')
- menu "Project", we have one line for this project
- menu "Project Detail", select 'Add version' and create a new version for this project 1.0.1  with the all include parameters (tags, properties, components, services, audit history). Need to add a parameter for permissions ?
- menu "Project", we have ONLY 1 line for this project. The choice to select a specific version is available in the project itself
- menu "Portfolio Access Control", the N teams are affected to the project (no permission per version ?)

Question : maybe the same behavior for automatic creation by maven for example ?

### Environment:
  
  - Dependency-Track Version: 4.3.2
  - Distribution: Docker
  - BOM Format & Version: All
  - Database Server: PostgreSQL
  - Browser: Chrome / FireFox

### Additional Details:

**Comment by valentijnscholten** [comment] 2022-05-18 18:39
duplicate of #1534.

**Closed** 2022-11-06 22:26 UTC
Labels: duplicate
