### ISSUE TITLE
Configurable task scheduling

### ISSUE THREAD

**Issue by hostalp** [DependencyTrack/dependency-track#978] opened 2021-03-21 02:06 UTC
### Current Behavior:
In our DT instance the **portfolio metrics update** task takes approx. 3.5 hours to complete (and it was even worse - approx. 9 hours at version 3.7.1) and since it's scheduled to execute every hour it's basically running all the time, consuming especially CPU resources.

In the past, when running the executable WAR variant I could easily patch the `org.dependencytrack.tasks.TaskScheduler` class where I simply increased the interval for this task, for example here:
https://github.com/DependencyTrack/dependency-track/blob/master/src/main/java/org/dependencytrack/tasks/TaskScheduler.java#L71
However with the now preferred container image variant this isn't that easy.

### Proposed Behavior:
Could you please make at least the execution interval of the most demanding tasks user-configurable (via properties / environment variables)?

**Comment by stevespringett** [comment] 2021-03-21 02:39
3.5 hours is an aweful long time. You may want to investigate the container host to ensure it's properly resourced and able to provide DT the resources it needs. You may also want to investigate the database server. Underpowered container hosts (even RDS instances) can greatly impact DT performance.

The number of threads DT allocates to metrics is 1. There are many other threads available to process work, assuming the host have a minimum of 2 CPUs (4 or more recommended).

**Comment by stevespringett** [comment] 2021-03-21 02:40
Configurable task scheduling would be a good enhancement. Pull requests are highly encouraged.

**Comment by hostalp** [comment] 2021-03-21 14:32
Yes I know, that particular host has pretty poor single-core performance, but it has many cores available. If the task could be effectively parallelized and performed in multiple threads that would help greatly.
We're going to migrate to a different hardware later this year which should help at least in our case.

Also it's a little annoying to see such task being executed after the restart even if it just successfully completed not a long time ago. E.g. application restart (or start) means that everything starts from the scratch and there isn't any sort of persistence that would handle this across restarts. Restarts aren't a common thing so it isn't a big issue, but it could be a nice improvement as well.

**Comment by syalioune** [comment] 2022-08-25 17:11
That request is a duplicate of [1542](https://github.com/DependencyTrack/dependency-track/issues/1542)

**Comment by nscuro** [comment] 2022-09-07 06:54
Implemented in #1841.

**Closed by nscuro** 2022-09-07 06:54 UTC
Labels: duplicate, enhancement, p3
