### ISSUE TITLE
NPE on notification using Email publisher

### ISSUE THREAD

**Issue by RaphC** [DependencyTrack/dependency-track#507] opened 2019-11-08 15:20 UTC
Hi

### Current Behavior:
I got a NPE while dependency-track try to notify after BOM processed

### Steps to Reproduce:
Configure an smtp
Add an alert (INFORMATIONAL on PORTOFOLIO) and then select BOM_PROCESSED
Upload a BOM from the UI and wait analysis performed

### Expected Behavior:
Received an email

### Environment:
  
  - Dependency-Track 3.6.1:
  - Distribution: Docker
  - BOM Format & Version: CycloneDx 1.1
  - Database Server: MySQL
  - Browser: chrome 

### Additional Details:

Seems  Email publisher attribute not set if I look at NotificationRouter.java:60 source code 

 final Class<?> publisherClass = Class.forName(rule.getPublisher().getPublisherClass());

![image](https://user-images.githubusercontent.com/1260364/68487985-62646600-0244-11ea-9c2b-f3822a105f89.png)

Whereas slack, console, webhook, microsoft teams publihser are ok

![image](https://user-images.githubusercontent.com/1260364/68488226-e3bbf880-0244-11ea-8745-b65e11704b9a.png)

Record in database seems ok

-----------------------------+
| ID | ENABLED | MESSAGE | NAME                | NOTIFICATION_LEVEL | NOTIFY_ON     | PUBLISHER | PUBLISHER_CONFIG                                | SCOPE     | UUID                                 |
+----+---------+---------+---------------------+--------------------+---------------+-----------+-------------------------------------------------+-----------+--------------------------------------+
|  1 |        | NULL    | swad-bom-processing | INFORMATIONAL      | BOM_PROCESSED |         3 | {"destination":"xxxxxxxxxx"} | PORTFOLIO | 91ac7634-1214-477d-94d3-d82770c3a667 |
|

15:08:48.139 ERROR [LoggableUncaughtExceptionHandler] An unknown error occurred in an asynchronous event or notification thread
java.lang.NullPointerException: null
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.dependencytrack.notification.NotificationRouter.inform(NotificationRouter.java:60)
        at alpine.notification.NotificationService.lambda$alertSubscriber$0(NotificationService.java:100)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by stevespringett** [comment] 2019-11-08 16:00
For some reason, the publisher is blank. I just tried with 3.6.1 and could not reproduce. 

<img width="1326" alt="Screen Shot 2019-11-08 at 9 58 08 AM" src="https://user-images.githubusercontent.com/3878933/68490387-7beabb00-020e-11ea-8cdc-cf5a2ada42c5.png">

**Comment by RaphC** [comment] 2019-11-08 17:37
Hi @stevespringett , after restarting dependency-track the problem was resolved. A cache ?

I notice if I edit my alert publisher is blank during a while and after a few seconds the correct value 'SendMailPublisher' appears ...

**Comment by RaphC** [comment] 2019-11-08 17:38
Or a database request latency that make join between NOTIFICATIONRULE and NOTIFICATIONPUBLISHER slow ?

**Comment by stevespringett** [comment] 2020-01-14 21:49
Closing

**Closed by stevespringett** 2020-01-14 21:49 UTC
Labels: in triage
