### ISSUE TITLE
OIDC  / JWT / AD: Users with a lot of group memberships cannot login 

### ISSUE THREAD

**Issue by Jasper-Ben** [DependencyTrack/dependency-track#3220] opened 2023-11-22 15:56 UTC
### Current Behavior

Dependencytrack relies on the `groups` attribute to be available in the JWT token, e.g.:

```
{
  "email": "Jasper.Orschulko@iris-sensing.com",
  "groups": [
    "dt_admin",
    ...
  ]
  ...
}
```

However, when a user is member of a lot(:tm:)  of groups, the maximum length of an URI request would be exceeded. To circumvent this, AD will offload this to other requests:

```
{
  "email": "John.Doe@iris-sensing.com",
  "_claim_names": {
    "groups": "src1"
  },
  "_claim_sources": {
    "src1": {
      "endpoint": "https://graph.windows.net/0180f800-1188-4fe5-8fc9-740e8dd3f1b6/users/85d949b6-0971-43c3-a663-381a012eba04/getMemberObjects"
    }
  }
}
```

This behavior is described here: https://stackoverflow.com/questions/45751985/aad-groups-claim-missing-in-jwt-token-for-some-users and in the linked documentation: https://learn.microsoft.com/en-us/azure/active-directory/develop/active-directory-token-and-claims & https://msdn.microsoft.com/library/azure/ad/graph/api/functions-and-actions#isMemberOf

### Steps to Reproduce

1. Setup OIDC with AD in DT
2. Have a user who is member of a sh*tton of AD groups
3. Watch that user not being able to login (403), even though he is member of appropriate group
4. Get the JWT token from the /login POST request (`idToken`) and paste it in https://jwt.io/

### Expected Behavior

DT should be able to handle to deal with a lot of AD groups (see linked documentation)

### Dependency-Track Version

4.9.1

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Browser

Mozilla Firefox

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment] 2023-11-22 16:18
The docs say this only applies to the `implicit` flow, which is discouraged anyway. I don't have XP with MS / Azure products, but is it not possible to use the Authorization Code (+PKCE) flow?

**Comment by Jasper-Ben** [comment] 2023-11-22 17:37
Good catch!

 Tbh I don't have any experience with Azure either, so I'm not sure what PKCE implies here. I'll forward this to ppl in my company who hopefully can provide some input in this matter and let you know. :)

**Comment by Jasper-Ben** [comment] 2023-11-23 12:10
Just had another look at the [dependencytrack oidc config](https://docs.dependencytrack.org/getting-started/configuration/#frontend) and if I understood it correctly, we should already be using PKCE, since we did not have `OIDC_FLOW` set beforehand:

>  // Optional
    // Specifies the OpenID Connect flow to use.
    // **Values other than "implicit" will result in the Code+PKCE flow to be used.**
    // Usage of the implicit flow is strongly discouraged, but may be necessary when
    // the IdP of choice does not support the Code+PKCE flow.
    // See also:
    //   - https://oauth.net/2/grant-types/implicit/
    //   - https://oauth.net/2/pkce/
   "OIDC_FLOW": "",

```
/opt/owasp/dependency-track-frontend $ env | grep OIDC
OIDC_ISSUER=https://login.microsoftonline.com/211fa99a-1f54-426b-b312-f9bc54784cc4/v2.0
OIDC_CLIENT_ID=ebcda565-6b05-4410-9ce7-2731c728fc84
OIDC_SCOPE=openid profile email
```

To be on the safe side, I tried setting `OIDC_FLOW=pkce` explicitly, but still the same behavior.

So at this point I see 2 possibilities:

1. the OIDC_FLOW variable does not do what it should and for some reason DT still uses implicit flow, or there is a bug in DTs OIDC implementation.
2. We understood the docs wrong and this behavior is also to be expected in a PKCE flow.

In any case, I think it is safe to say that this is indeed a defect in DT.

@martin31821 has quite some experience with OIDC, maybe he can give some more input here.

**Comment by nscuro** [comment] 2023-11-23 12:37
> the OIDC_FLOW variable does not do what it should and for some reason DT still uses implicit flow, or there is a bug in DTs OIDC implementation.

The flow being used should be verifyable by observing the output in your browser's developer tools "Network" tab, during authentication. If `implicit` was used, you'd see a token in the URL when you're redirected from the IdP back to DT. I doubt this is happening, but of course can't fully rule it out without testing it.

> We understood the docs wrong and this behavior is also to be expected in a PKCE flow.
> In any case, I think it is safe to say that this is indeed a defect in DT.

Not trying to be overly defensive here, but Microsoft doing things outside the OIDC spec (requiring an extra round-trip to their proprietary graph API), and DT not supporting that, is not a defect in DT. Other IdPs that properly follow the spec are working just fine. We can work on supporting that anyway of course.

**Comment by Jasper-Ben** [comment] 2023-11-23 13:03
> Not trying to be overly defensive here, but Microsoft doing things outside the OIDC spec (requiring an extra round-trip to their proprietary graph API), and DT not supporting that, is not a defect in DT. Other IdPs that properly follow the spec are working just fine. We can work on supporting that anyway of course.

You got a point there. Also, I didn't mean it in an accusatory way, more as a "This is something that we would have to fix in DT for getting it to work". Sorry, sounded harsher than intended.

> The flow being used should be verifyable by observing the output in your browser's developer tools "Network" tab, during authentication. If implicit was used, you'd see a token in the URL when you're redirected from the IdP back to DT. I doubt this is happening, but of course can't fully rule it out without testing it.

Not sure if I understood this 100% correct, but I think this **is** the case. After login in AD we get redirected to DT and there we get another POST to `/login`, with the JWT token as part of the request. In another application we use with AD I wasn't able to find a similar request.

**Comment by nscuro** [comment] 2023-11-23 13:09
> Not sure if I understood this 100% correct, but I think this is the case.

There should be a request in your Network history that redirects from Azure (where you entered your SSO credentials), back to DT. The request should go to `/oidc-callback.html` on the host that runs the DT frontend. In that request, if the `implicit` flow was used, you'd see a JWT token *in the request URL*. 

If instead you see a `code` query parameter, then the authorization code flow is used. In that case, there should be an additional request to Azure, where the token is exchanged for the actual JWT token.

The POST to `/login` is performed with the tokens acquired from the IdP. So at that point the token exchange already happened.

**Comment by nscuro** [comment] 2023-11-25 17:18
FWIW I believe this is a duplicate of https://github.com/DependencyTrack/dependency-track/issues/2150.

**Comment by Jasper-Ben** [comment] 2023-11-25 19:33
Agreed, seems like it. Thanks for the heads-up. 👍 Will close this.

**Closed** 2023-11-25 19:34 UTC
Labels: defect, in triage
