### ISSUE TITLE
Next major prerelease is shown as available update

### ISSUE THREAD

**Issue by fluorumlabs** [DependencyTrack/dependency-track#1049] opened 2021-05-20 07:39 UTC
Suppose that project uses dependency XXX version 1.7 and the latest released version is 2.0-alpha1.

### Current Behavior:

Version 2.0-alpha1 is shown in the yellow triangle tooltip.

### Expected Behavior:

Version 1.7 is marked as latest

### Environment:
  
  - Dependency-Track Version: 4.22
  - Distribution: Docker
  - BOM Format & Version: CycloneDX 1.2 JSON

**Comment by stevespringett** [comment] 2021-05-20 21:22
Duplicate of #513

PRs are highly welcome.

**Closed by stevespringett** 2021-05-20 21:22 UTC
Labels: duplicate
