### ISSUE TITLE
H2 Database error preventing Dependency Track to run

### ISSUE THREAD

**Issue by VikraKrish** [DependencyTrack/dependency-track#3844] opened 2024-06-13 13:45 UTC
### Current Behavior

![DBError](https://github.com/DependencyTrack/dependency-track/assets/136571368/4d45bfa6-daad-49b9-8785-d6e4bd0dd232)

I get the below error when trying to run the Dependency tracker. Any help would be appreciated on how to resolve this issue. 

### Steps to Reproduce

1. Tried installing DT using Docker Compose (default DB config)
2. Both the front end and API server is UP
3. But the app fetched error when loaded in browser
4. On checking the logs, it threw some H2 database error 

### Expected Behavior

The app should be loading properly in the browser.

### Dependency-Track Version

4.11.0

### Dependency-Track Distribution

Container Image

### Database Server

H2

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment] 2024-06-15 16:40
Duplicate of #2061. However, a restart should fix this particular issue. It's a race condition. A fix is being worked on, see the linked issue.

**Closed by nscuro** 2024-06-15 16:40 UTC
Labels: duplicate
